In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
pd.options.display.max_columns = 999

%matplotlib inline

In [2]:
PROVIDER ="..\data\Medicare_Provider_Util_Payment_PUF_CY2017.txt"

In [3]:
#?pd.read_csv

In [4]:
pd.read_csv(PROVIDER, sep='\t', nrows=100).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   npi                               100 non-null    int64
 1   nppes_provider_last_org_name      100 non-null    object
 2   nppes_provider_first_name         99 non-null     object
 3   nppes_provider_mi                 67 non-null     object
 4   nppes_credentials                 99 non-null     object
 5   nppes_provider_gender             99 non-null     object
 6   nppes_entity_code                 99 non-null     object
 7   nppes_provider_street1            99 non-null     object
 8   nppes_provider_street2            68 non-null     object
 9   nppes_provider_city               99 non-null     object
 10  nppes_provider_zip                99 non-null     float64
 11  nppes_provider_state              99 non-null     object
 12  nppes_provider_country            99 non-null     object
 13  provider_type                     99 non-null     object
 14  medicare_participation_indicator  99 non-null     object
 15  place_of_service                  99 non-null     object
 16  hcpcs_code                        99 non-null     object
 17  hcpcs_description                 99 non-null     object
 18  hcpcs_drug_indicator              99 non-null     object
 19  line_srvc_cnt                     99 non-null     float64
 20  bene_unique_cnt                   99 non-null     float64
 21  bene_day_srvc_cnt                 99 non-null     float64
 22  average_Medicare_allowed_amt      99 non-null     float64
 23  average_submitted_chrg_amt        99 non-null     float64
 24  average_Medicare_payment_amt      99 non-null     float64
 25  average_Medicare_standard_amt     99 non-null     float64
dtypes: float64(8), int64(1), object(17)
memory usage: 20.4+ KB

In [33]:
#reading text file in chunks
pd.read_csv(PROVIDER,
    sep='\t',
    nrows= 100000,
    usecols=['npi','nppes_provider_last_org_name',
             'nppes_provider_first_name','nppes_provider_mi','nppes_credentials' ,
             'nppes_entity_code','place_of_service','provider_type',
             'nppes_provider_zip','nppes_provider_city','nppes_provider_state',
             'hcpcs_code','hcpcs_description','bene_unique_cnt',
             'average_Medicare_allowed_amt','average_Medicare_payment_amt'],
    dtype ={'nppes_provider_zip': 'str'}
).dtypes

npi                               int64
nppes_provider_last_org_name     object
nppes_provider_first_name        object
nppes_provider_mi                object
nppes_credentials                object
nppes_entity_code                object
nppes_provider_city              object
nppes_provider_zip               object
nppes_provider_state             object
provider_type                    object
place_of_service                 object
hcpcs_code                       object
hcpcs_description                object
bene_unique_cnt                 float64
average_Medicare_allowed_amt    float64
average_Medicare_payment_amt    float64
dtype: object

In [6]:
# read the df starting index 1 and reset index
#provider = provider.iloc[1:]
#provider = provider.reset_index(drop=True)

In [39]:
provider_chunks = pd.read_csv(
    PROVIDER,
    sep='\t',
    chunksize= 100000,
    usecols=['npi','nppes_provider_last_org_name',
             'nppes_provider_first_name','nppes_provider_mi','nppes_credentials' ,
             'nppes_entity_code','place_of_service','provider_type',
             'nppes_provider_zip','nppes_provider_city','nppes_provider_state',
             'hcpcs_code','hcpcs_description','bene_unique_cnt',
             'average_Medicare_allowed_amt','average_Medicare_payment_amt'],
    dtype = {'npi':'str','nppes_provider_zip': 'str'}
)

In [40]:
#def filter_data(column):
filtered_dataset = []
for i, chunk in enumerate(provider_chunks):
    print(i +1)
    filtered_dataset.append(chunk[chunk['provider_type'] == 'Ambulatory Surgical Center'])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

In [43]:
dataset =pd.concat(filtered_dataset)
type(dataset)

pandas.core.frame.DataFrame

In [44]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57329 entries, 2912 to 9847425
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   npi                           57329 non-null  object
 1   nppes_provider_last_org_name  57329 non-null  object
 2   nppes_provider_first_name     0 non-null      object
 3   nppes_provider_mi             0 non-null      object
 4   nppes_credentials             0 non-null      object
 5   nppes_entity_code             57329 non-null  object
 6   nppes_provider_city           57329 non-null  object
 7   nppes_provider_zip            57329 non-null  object
 8   nppes_provider_state          57329 non-null  object
 9   provider_type                 57329 non-null  object
 10  place_of_service              57329 non-null  object
 11  hcpcs_code                    57329 non-null  object
 12  hcpcs_description             57329 non-null  object
 13  bene_unique_cnt               57329 non-null  float64
 14  average_Medicare_allowed_amt  57329 non-null  float64
 15  average_Medicare_payment_amt  57329 non-null  float64
dtypes: float64(3), object(13)
memory usage: 7.4+ MB

In [45]:
dataset_reset = dataset.reset_index(drop=True)

In [46]:
dataset_reset['provider_zip'] = dataset_reset.nppes_provider_zip.str[:5]   
provider = dataset_reset.drop(['nppes_provider_zip'], axis=1)

In [47]:
#def wavg(group, avg_name, weight_name):
 #   """ http://stackoverflow.com/questions/10951341/pandas-dataframe-aggregate-function-using-multiple-columns
  #  In rare instance, we may not have weights, so just return the mean. Customize this if your business case
   # should return otherwise.
    #"""
    #d = group[avg_name]
    #w = group[weight_name]
    #try:
     #   return (d * w).sum() / w.sum()
    #except ZeroDivisionError:
     #   return d.mean()"""

In [48]:
provider.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_entity_code,nppes_provider_city,nppes_provider_state,provider_type,place_of_service,hcpcs_code,hcpcs_description,bene_unique_cnt,average_Medicare_allowed_amt,average_Medicare_payment_amt,provider_zip
0,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,O,VACAVILLE,CA,Ambulatory Surgical Center,F,0191T,Internal insertion of eye fluid drainage device,11.0,3042.237692,2385.113846,95687
1,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,O,VACAVILLE,CA,Ambulatory Surgical Center,F,20610,Aspiration and/or injection of large joint or ...,14.0,26.260000,20.588947,95687
2,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,O,VACAVILLE,CA,Ambulatory Surgical Center,F,29823,Extensive removal of shoulder joint tissue usi...,15.0,837.130000,656.310000,95687
3,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,O,VACAVILLE,CA,Ambulatory Surgical Center,F,29824,Partial removal of collar bone at shoulder usi...,14.0,1016.512857,796.945714,95687
4,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,O,VACAVILLE,CA,Ambulatory Surgical Center,F,29827,Repair of shoulder rotator cuff using an endos...,22.0,3391.399545,2652.337273,95687

In [49]:
provider.groupby(['nppes_provider_last_org_name','hcpcs_code', 'nppes_entity_code','provider_zip']).agg({'average_Medicare_allowed_amt':['mean', 'min','max']})

                                                                                 average_Medicare_allowed_amt  \
                                                                                                         mean
nppes_provider_last_org_name           hcpcs_code nppes_entity_code provider_zip
1800 MCDONOUGH ROAD SURGERY CENTER LLC 62321      O                 60192                          275.030000
                                       62323      O                 60192                          272.483519
                                       64450      O                 60192                           29.459467
                                       64483      O                 60192                          300.997125
                                       64490      O                 60192                          329.147000
...                                                                                                       ...
ZITELLI & BRODLAND PC                  17311      O                 15025                          182.612687
                                                                    15232                          184.207859
                                       17313      O                 15025                          204.782545
                                                                    15232                          195.102625
                                       21235      O                 15025                         1752.272727

                                                                                               \
                                                                                          min
nppes_provider_last_org_name           hcpcs_code nppes_entity_code provider_zip
1800 MCDONOUGH ROAD SURGERY CENTER LLC 62321      O                 60192          275.030000
                                       62323      O                 60192          272.483519
                                       64450      O                 60192           29.459467
                                       64483      O                 60192          300.997125
                                       64490      O                 60192          329.147000
...                                                                                       ...
ZITELLI & BRODLAND PC                  17311      O                 15025          182.612687
                                                                    15232          184.207859
                                       17313      O                 15025          204.782545
                                                                    15232          195.102625
                                       21235      O                 15025         1752.272727


                                                                                          max
nppes_provider_last_org_name           hcpcs_code nppes_entity_code provider_zip
1800 MCDONOUGH ROAD SURGERY CENTER LLC 62321      O                 60192          275.030000
                                       62323      O                 60192          272.483519
                                       64450      O                 60192           29.459467
                                       64483      O                 60192          300.997125
                                       64490      O                 60192          329.147000
...                                                                                       ...
ZITELLI & BRODLAND PC                  17311      O                 15025          182.612687
                                                                    15232          184.207859
                                       17313      O                 15025          204.782545
                                                                    15232          195.102625
                                       21235      O                 15025         1752.272727

[57283 rows x 3 columns]

In [52]:
hcpcs_apc = pd.read_csv('..\data\hcpcs_apc.csv')
hcpcs_apc = hcpcs_apc.rename(columns={'HCPCS Code': 'hcpcs_code'})
hcpcs_apc.head()

  hcpcs_code   APC
0      10005  5071
1      10007  5071
2      10009  5071
3      10011  5071
4      10021  5052

In [54]:
provider_APC = pd.merge(provider, hcpcs_apc, on='hcpcs_code', how = 'inner')

In [55]:
provider_APC.tail()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_entity_code,nppes_provider_city,nppes_provider_state,provider_type,place_of_service,hcpcs_code,hcpcs_description,bene_unique_cnt,average_Medicare_allowed_amt,average_Medicare_payment_amt,provider_zip,APC
56479,1962869826,"ENDOTECH, LLC",NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,29845,Removal of wrist joint lining using an endoscope,23.0,690.658750,541.481250,85260,5113
56480,1962869826,"ENDOTECH, LLC",NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,64910,Repair of nerve with graft,83.0,1708.530000,1338.195586,85260,5432
56481,1972711612,BALTIMORE- HARFORD SURGICAL CENTERS,NaN,NaN,NaN,O,BEL AIR,MD,Ambulatory Surgical Center,F,64566,Implantation of lower leg neurostimulator elec...,24.0,103.660000,76.785818,21014,5441
56482,1982676771,"SHREVEPORT ENDOSCOPY CENTER, A MEDICAL CORPORA...",NaN,NaN,NaN,O,SHREVEPORT,LA,Ambulatory Surgical Center,F,49082,Drainage of fluid from abdominal cavity,24.0,357.956296,272.664630,71103,5301
56483,1992752224,SPRINGFIELD CLINIC LLP,NaN,NaN,NaN,O,SPRINGFIELD,IL,Ambulatory Surgical Center,F,32550,Insertion of permanent catheter for drainage o...,11.0,1399.040000,1096.850000,62703,5341

In [81]:
#provider_APC.groupby('APC').hcpcs_code.count()

In [84]:
##### df.loc[df['column_name'] == some_value]
#provider_APC.groupby(['hcpcs_code','APC', 'nppes_entity_code','nppes_provider_state','hcpcs_description']).agg({'bene_unique_cnt': ['count','mean', 'min','max']})

In [86]:
#df.loc[df['A'] == 'foo']
#gdp_internet_2004 = gdp_combined[gdp_combined['Year']==2004]
#gdp_internet_2004.shape
APC_5743 =provider_APC[provider_APC['provider_zip']=='85260']
APC_5743.shape

(100, 17)

In [88]:
APC_5743.head(n=100)

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_entity_code,nppes_provider_city,nppes_provider_state,provider_type,place_of_service,hcpcs_code,hcpcs_description,bene_unique_cnt,average_Medicare_allowed_amt,average_Medicare_payment_amt,provider_zip,APC
721,1154326650,SCOTTSDALE SURGICAL PARTNERS LLC,NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,20610,Aspiration and/or injection of large joint or ...,25.0,25.494516,19.984839,85260,5441
992,1598968927,"THE ORTHOPEDIC CLINIC ASSOCIATION, P.C.",NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,20610,Aspiration and/or injection of large joint or ...,18.0,29.270000,21.987083,85260,5441
1173,1902807159,"SURGERY CENTER OF SCOTTSDALE, LLC",NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,20610,Aspiration and/or injection of large joint or ...,123.0,24.866796,18.491521,85260,5441
1281,1154326650,SCOTTSDALE SURGICAL PARTNERS LLC,NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,29823,Extensive removal of shoulder joint tissue usi...,24.0,785.814800,616.081200,85260,5113
1675,1154326650,SCOTTSDALE SURGICAL PARTNERS LLC,NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,29824,Partial removal of collar bone at shoulder usi...,61.0,742.643065,579.921613,85260,5113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56060,1962869826,"ENDOTECH, LLC",NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,25020,Incision of tissue of forearm and/or wrist mus...,112.0,350.310000,273.643681,85260,5112
56226,1962869826,"ENDOTECH, LLC",NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,64702,Release of nerve of finger,16.0,456.962500,358.258000,85260,5431
56478,1962869826,"ENDOTECH, LLC",NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,25075,Removal (less than 3 centimeters) tissue growt...,14.0,393.895000,308.815000,85260,5072
56479,1962869826,"ENDOTECH, LLC",NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,29845,Removal of wrist joint lining using an endoscope,23.0,690.658750,541.481250,85260,5113
56480,1962869826,"ENDOTECH, LLC",NaN,NaN,NaN,O,SCOTTSDALE,AZ,Ambulatory Surgical Center,F,64910,Repair of nerve with graft,83.0,1708.530000,1338.195586,85260,5432

In [95]:
provider_APC.groupby(['hcpcs_code', 'APC']).average_Medicare_allowed_amt.max()

hcpcs_code  APC
0191T       5492     3721.010000
0253T       5492     2227.570000
0275T       5114     3009.120000
0408T       5231    15894.240000
0449T       5492     2700.250000
                        ...
J7325       874        12.707059
J7327       1747      890.596154
J9035       9214       75.102456
J9280       1232      122.572667
Q9968       1446        3.410000
Name: average_Medicare_allowed_amt, Length: 926, dtype: float64

In [117]:
hcpcs_apc_filter = pd.read_csv('..\data\APCs_in_Outpatient.csv', dtype={'APC':'str'})
hcpcs_apc_filter.head()

  hcpcs_code   APC
0      10005  5071
1      10007  5071
2      10009  5071
3      10011  5071
4      10021  5052

In [118]:
hcpcs_apc_filter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5942 entries, 0 to 5941
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hcpcs_code  5942 non-null   object
 1   APC         5942 non-null   object
dtypes: object(2)
memory usage: 93.0+ KB

In [119]:
hcpcs_apc_filter.shape

(5942, 2)

In [120]:
provider_hcpcs_apc = pd.merge(provider, hcpcs_apc_filter, on='hcpcs_code', how='left')

In [121]:
provider_hcpcs_apc.shape

(57329, 17)

In [125]:
provider_hcpcs_apc.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_entity_code,nppes_provider_city,nppes_provider_state,provider_type,place_of_service,hcpcs_code,hcpcs_description,bene_unique_cnt,average_Medicare_allowed_amt,average_Medicare_payment_amt,provider_zip,APC
0,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,O,VACAVILLE,CA,Ambulatory Surgical Center,F,0191T,Internal insertion of eye fluid drainage device,11.0,3042.237692,2385.113846,95687,5492
1,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,O,VACAVILLE,CA,Ambulatory Surgical Center,F,20610,Aspiration and/or injection of large joint or ...,14.0,26.260000,20.588947,95687,5441
2,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,O,VACAVILLE,CA,Ambulatory Surgical Center,F,29823,Extensive removal of shoulder joint tissue usi...,15.0,837.130000,656.310000,95687,5113
3,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,O,VACAVILLE,CA,Ambulatory Surgical Center,F,29824,Partial removal of collar bone at shoulder usi...,14.0,1016.512857,796.945714,95687,5113
4,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,O,VACAVILLE,CA,Ambulatory Surgical Center,F,29827,Repair of shoulder rotator cuff using an endos...,22.0,3391.399545,2652.337273,95687,5114

In [131]:
#males = df[(df[Gender]=='Male') & (df[Year]==2014)]
provider_hcpcs_43249 = provider_hcpcs_apc[(provider_hcpcs_apc.hcpcs_code=='43249') & (provider_hcpcs_apc.nppes_entity_code=='O')]

In [132]:
provider_hcpcs_43249.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 616 entries, 9 to 57276
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   npi                           616 non-null    object
 1   nppes_provider_last_org_name  616 non-null    object
 2   nppes_provider_first_name     0 non-null      object
 3   nppes_provider_mi             0 non-null      object
 4   nppes_credentials             0 non-null      object
 5   nppes_entity_code             616 non-null    object
 6   nppes_provider_city           616 non-null    object
 7   nppes_provider_state          616 non-null    object
 8   provider_type                 616 non-null    object
 9   place_of_service              616 non-null    object
 10  hcpcs_code                    616 non-null    object
 11  hcpcs_description             616 non-null    object
 12  bene_unique_cnt               616 non-null    float64
 13  average_Medicare_allowed_amt  616 non-null    float64
 14  average_Medicare_payment_amt  616 non-null    float64
 15  provider_zip                  616 non-null    object
 16  APC                           616 non-null    object
dtypes: float64(3), object(14)
memory usage: 86.6+ KB

In [145]:
provider_hcpcs_43249.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_entity_code,nppes_provider_city,nppes_provider_state,provider_type,place_of_service,hcpcs_code,hcpcs_description,bene_unique_cnt,average_Medicare_allowed_amt,average_Medicare_payment_amt,provider_zip,APC
9,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,O,VACAVILLE,CA,Ambulatory Surgical Center,F,43249,Balloon dilation of esophagus using an endoscope,16.0,814.53450,596.400500,95687,5302
76,1003079187,WASC LLC,NaN,NaN,NaN,O,WOOSTER,OH,Ambulatory Surgical Center,F,43249,Balloon dilation of esophagus using an endoscope,15.0,555.31000,433.162941,44691,5302
221,1003220187,"CENTRAL OHIO ENDOSCOPY CENTER, LLC",NaN,NaN,NaN,O,COLUMBUS,OH,Ambulatory Surgical Center,F,43249,Balloon dilation of esophagus using an endoscope,79.0,596.51000,463.132234,43202,5302
325,1003815242,"DOTHAN SURGERY CENTER, LLC",NaN,NaN,NaN,O,DOTHAN,AL,Ambulatory Surgical Center,F,43249,Balloon dilation of esophagus using an endoscope,409.0,509.85778,391.675538,36301,5302
502,1003887225,CENTRAL TEXAS ENDOSCOPY CENTER LLC,NaN,NaN,NaN,O,BRYAN,TX,Ambulatory Surgical Center,F,43249,Balloon dilation of esophagus using an endoscope,23.0,576.83000,445.692692,77802,5302

In [146]:
zip_cbsa = pd.read_excel('..\data\ZIP_CBSA_032020.xlsx', dtype ={'ZIP': 'str', 'CBSA': 'str'})
zip_cbsa = zip_cbsa.loc[:, ['ZIP', 'CBSA']]
zip_cbsa

         ZIP   CBSA
0      00501  35620
1      00601  38660
2      00602  10380
3      00603  10380
4      00604  10380
...      ...    ...
47410  99925  99999
47411  99926  99999
47412  99927  99999
47413  99928  28540
47414  99929  99999

[47415 rows x 2 columns]

In [147]:
provider_hcpcs_43249_CBSA = pd.merge(provider_hcpcs_43249, zip_cbsa, left_on = 'provider_zip', right_on='ZIP', how= 'left')
provider_hcpcs_43249_CBSA.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 682 entries, 0 to 681
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   npi                           682 non-null    object
 1   nppes_provider_last_org_name  682 non-null    object
 2   nppes_provider_first_name     0 non-null      object
 3   nppes_provider_mi             0 non-null      object
 4   nppes_credentials             0 non-null      object
 5   nppes_entity_code             682 non-null    object
 6   nppes_provider_city           682 non-null    object
 7   nppes_provider_state          682 non-null    object
 8   provider_type                 682 non-null    object
 9   place_of_service              682 non-null    object
 10  hcpcs_code                    682 non-null    object
 11  hcpcs_description             682 non-null    object
 12  bene_unique_cnt               682 non-null    float64
 13  average_Medicare_allowed_amt  682 non-null    float64
 14  average_Medicare_payment_amt  682 non-null    float64
 15  provider_zip                  682 non-null    object
 16  APC                           682 non-null    object
 17  ZIP                           682 non-null    object
 18  CBSA                          682 non-null    object
dtypes: float64(3), object(16)
memory usage: 106.6+ KB

In [75]:
#df["Name"] = df["First"] +" "+ df["Last"]
provider_apc_not_5302 = provider_hcpcs_43249_CBSA[provider_hcpcs_43249_CBSA.APC != '5302']
provider_apc_not_5302.shape

(0, 19)

In [66]:
provider_apc_5302 = provider_hcpcs_43249_CBSA[provider_hcpcs_43249_CBSA.APC == '5302']
provider_apc_5302.to_csv('provider_apc_5302.csv', index=False)

In [67]:
#provider_hcpcs_43249_CBSA.head(n=20)

In [68]:
#gb = provider_hcpcs_43249_CBSA.groupby(['CBSA']).get_group('41940')
#gb_ca = gb.get_group
#gb.get_group(['nppes_provider_state'=='CA', 'CBSA'== '41940'])
#gb.shape

In [69]:
#gb